# Key for printing coords inputs to place marble
PRINT_BOARD_PLACE_MARBLE = "PRINT_BOARD_PLACE_MARBLE"
# Key for printing rotation inputs to rotate a quarter
PRINT_BOARD_ROTATE = "PRINT_BOARD_ROTATE"

# Key for printing board in finished mode
PRINT_BOARD_FINISHED = "PRINT_BOARD_FINISHED"

COLOR_RESET = "\u001b[0m"
COLOR_YELLOW = "\u001b[33m"
COLOR_CYAN = "\u001b[36m"

UNPLAYED_CHARACTER = "◯"
PLAYER_CHARACTER = "◉"
PLAYER_ALIGNMENT_CHARACTER = "♦"


BASE_NUMBER_OF_SPACES = 6
BASE_SPACES = " " * BASE_NUMBER_OF_SPACES
MINIMAL_SPACES_PLAYER = 4
